### ISSUE TITLE
Swift 2.0 support

### ISSUE THREAD

**Issue by plashchynski** [master-nevi/UPnAtom#15]
Any progress on that?

**Comment by master-nevi** [comment]
It's on a private branch right now. It'll be available shortly after the release of Xcode 7.

**Comment by plashchynski** [comment]
Hello. XCode 7 has released.

**Comment by master-nevi** [comment]
Yep thanks for the update. I've been busy at work so it's been slow moving in this project recently. Keep in mind that I'm not just running the migration tool, but also trying to fix old bugs that old language features introduced as well as use new language features to improve the way UPnAtom works. Please be patient.

**Comment by smith288** [comment]
lol.

**Comment by nervlord** [comment]
Really looking forward to it. Thanks very much.

**Comment by zbrox** [comment]
+1 for this as well

**Comment by noahfradin** [comment]
+1 any updates?

**Comment by master-nevi** [comment]
I'm glad to announce that Swift 2.1 compatibility is now available in [this branch](https://github.com/master-nevi/UPnAtom/tree/swift-2.1)! Due to [this bug](https://github.com/CocoaPods/CocoaPods/issues/4420) in the latest version of CocoaPods v0.39.0, I won't be able to publish a version yet. This bug is fixed in master, so I'm going to take the time to make more improvements and use more new language features until the next version of CocoaPods is released. Thanks for your patience!

**Comment by zbrox** [comment]
I tried installing that branch, but it wouldn't build. The error is the following

```[..]/Pods/Ono/Source/Ono.h:31:9: Include of non-modular header inside framework module 'Ono.Ono'```

**Comment by zbrox** [comment]
Just a heads up that CocoaPods 1.0 is now officially available

**Comment by master-nevi** [comment]
Fixed in 0.7.0
